routes/web.php
    <?php

    /*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    Route::get('/', function () {
    return view('welcome');
        });

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');


     //question

    Route::resource('questions', 'QuestionController')  ->except('show');

    Route::get('questions/{slug}','QuestionController@show')->name('questions.show');

    //answer

    Route::resource('questions.answers', 'AnswerController')  ->except(['index','create','show']);


    //Accept-Answer-Controller

    Route::post('/answers/{answer}/accept', 'AcceptAnswerController@accept')->name('accept.answers');


    //Questions favorites

    Route::post('/questions/{question}/favorites', 'FavoritesController@store') -> name('questions.favorite');

    Route::delete('/questions/{question}/favorites', 'FavoritesController@destroy') -> name('questions.unfavorite');


     //questions  vote +1,-1
    Route::post('/questions/{question}/vote', 'VoteQuestionController@vote') -> name('questions.vote');


    //answers vote +1, -1

    Route::post('/answers/{answer}/vote', 'VoteAnswerController@vote') -> name('answers.vote');

app/Answer.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Null_;

class Answer extends Model
{


  // Mass Assignment

 //   protected $fillable= ['body','user->id'];




  //One To Many (Inverse)

  public  function user(){

    return $this->belongsTo('App\User');
  }


  //One To Many (Inverse)

  public function question(){

    return $this->belongsTo('App\Question');

  }


  // question body parse akhane disi
  public function getBodyHtmlAttribute(){

    return clean(\Parsedown::instance()->text($this->body));

  }


  // Answer increment , over right

  public  static function boot()
  {
    parent::boot();
    static::created(function ($answer) {
      $answer->question->increment('answers_count');

    });


    static::deleted(function ($answer){
//       $answer->question->decrement('answers_count');

      //  kau best answer delete kore dile  onno arekta select korte parbo,atar jonna


        $question = $answer->question;
        $question->decrement('answers_count');
        if($question->best_answer_id === $answer->id){
            $question-> best_answer_id = NULL;
            $question->save();
        }


    });


  }




  //date Eloqurent

  public function getCreateDateAttribute($value)
  {
    return $this->created_at->diffForhumans() ;
  }




        //best answer select
      public function  getStatusAttribute(){

          return $this->id===$this->question->best_answer_id ? 'vote-accept' : '';

      }

      // best answer dekte parbo,jokn j question korce o best answer select korce
    public function getIsBestAttribute(){
        return $this->id === $this->question->best_answer_id ;
    }



    //Many To Many Polymorphic Relations, topic question and answer vote

    public function votes(){
        return $this->morphToMany(User::class,'votable')->withTimestamps();
    }



    public function  upVotes(){
        return $this->votes()->wherePivot('vote',1);
    }


    public function  downVotes(){
        return $this->votes()->wherePivot('vote',-1);
    }





//$appends ar kaj holo vue te jaigula undefined oigula pauano,jaigula elloqurent oigula pauano
    protected $appends=['create_date','body_html'];








}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;


use App\Answer;
use Illuminate\Http\Request;
use App\Question;
use App\Http\Requests\AnswerRequest;
use Illuminate\Support\Facades\Auth;
use App\User;



class AnswerController extends Controller
{



  public function __construct(){
    return $this->middleware('CheckRole');
  }




  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(AnswerRequest $request,Question $question)
  {

//        $question->answers()->create($request->validate(['body'=>'required'])
//            +['user_id'=>\Auth::id()]);			//answers holo model a method
//
//        return back()->with('success','Answer submitted');




    $questions= new Answer();
    $questions->user_id=Auth::id();
    $questions->question_id=$question->id;
    $questions->body=$request['body'];
    $questions->save();
    return back()->with('Your Answer submitted Successfully');





//
//        $answer= new Answer();
//        $answer->user_id=Auth::id();
//        $answer->question_id=$question->id;
//        $answer->body=$request['body'];
//        $answer->save();
//        return back()->with('Your Answer submitted Successfully');








  }



  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Answer  $answer
  * @return \Illuminate\Http\Response
  */

  public function edit(Question $question, Answer $answer)
  {

    $this->authorize('update',$answer);

    $question->user_id=Auth::id();
    $answer->user_id=Auth::id();
    $question->question_id=$question->id;

    return view('answers.edit',compact('question','answer'));


//        $question->question_id=$question->id;
//        $question->user_id=Auth::id();
//        $answer->delete();
//        return back()->with('success',' Answer successfully deleted');



  }



  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Answer  $answer
  * @return \Illuminate\Http\Response
  */



  public function update(AnswerRequest $request,Question $question, Answer $answer)
  {


    $this->authorize('update', $answer);


    $question->user_id=Auth::id();
    $answer->user_id=Auth::id();
    $question->question_id=$question->id;

    $answer->body=$request['body'];
    $answer->save();

      if($request->expectsJson()){
          return response()->json([
              'message'=> 'Answer updated Successfully',
              'body_html' => $answer->body_html
          ]);
      }


    return redirect()-> route('questions.show',$question->slug)->with('success',' Answer Updated');


  }



  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Answer  $answer
  * @return \Illuminate\Http\Response
  */



  public function destroy(Question $question ,Answer $answer)
  {



//        $this->authorize('delete',$answer);
//        $answer->delete();
//        return back()->with('success','Delete Successfully') ;
//


    $this->authorize('delete', $answer);
    $question->user_id=Auth::id();
    $answer->user_id=Auth::id();
    $question->question_id=$question->id;
    $answer->delete();


      if(request()->expectsJson()){
          return response()->json([
              'message'=> 'Answer Delete SUCCESSFULLY'
          ]);
      }


    return back()->with('success','Your Answer Deleted');
  }




}

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('content')

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 ">
        <div class="card ">
          <div class="card-header">

            <div class="float-left font-weight-bold"> <h3> Edit Answer</h3> </div>


            <div class="d-flex float-right">
              <a href="{{route('questions.show',$question->slug)}}" class="btn btn-outline-success">Back</a>

            </div>

          </div>


          <div class="card-body">
            <div class="media">

              <div class="media-body">


                @if($errors->any())
                  <div class="alert alert-danger">
                    <ul>
                      @foreach($errors->all() as $error)
                        <li>{{$error}}</li>
                      @endforeach
                    </ul>
                  </div>
                @endif

                @if(Session::has('success'))
                  <div class="alert alert-success">
                    {{Session::get('success')}}
                  </div>
                @endif


   {{--    action="{{route('questions.answers.update',[$question->id,$answer->id])}}--}}


                <form    action="{{route('questions.answers.update',[$question->id,$answer->id])}}"  method="post">
                  @method('PUT')
                  @csrf


                  <div class="form-group">
                    <label class="control-label">Update answer</label>

                    <textarea  name="body" class="form-control" rows="7" placeholder="Enter your Quetion">{{$answer->body}}</textarea>



                  </div>



                  <button type="submit" class="btn btn-outline-success">Update & save your Answer</button>


                </form>

              </div>

            </div>

          </div>




        </div>
      </div>
    </div>
  </div>

@endsection