routes/web.php
    <?php

    /*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    Route::get('/', function () {
    return view('welcome');
        });

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');


     //question

    Route::resource('questions', 'QuestionController')  ->except('show');

    Route::get('questions/{slug}','QuestionController@show')->name('questions.show');

    //answer

    Route::resource('questions.answers', 'AnswerController')  ->except(['index','create','show']);


    //Accept-Answer-Controller

    Route::post('/answers/{answer}/accept', 'AcceptAnswerController@accept')->name('accept.answers');


    //Questions favorites

    Route::post('/questions/{question}/favorites', 'FavoritesController@store') -> name('questions.favorite');

    Route::delete('/questions/{question}/favorites', 'FavoritesController@destroy') -> name('questions.unfavorite');


     //questions  vote +1,-1
    Route::post('/questions/{question}/vote', 'VoteQuestionController@vote') -> name('questions.vote');


    //answers vote +1, -1

    Route::post('/answers/{answer}/vote', 'VoteAnswerController@vote') -> name('answers.vote');

app/Answer.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Null_;

class Answer extends Model
{


  // Mass Assignment

 //   protected $fillable= ['body','user->id'];




  //One To Many (Inverse)

  public  function user(){

    return $this->belongsTo('App\User');
  }


  //One To Many (Inverse)

  public function question(){

    return $this->belongsTo('App\Question');

  }


  // question body parse akhane disi
  public function getBodyHtmlAttribute(){

    return clean(\Parsedown::instance()->text($this->body));

  }


  // Answer increment , over right

  public  static function boot()
  {
    parent::boot();
    static::created(function ($answer) {
      $answer->question->increment('answers_count');

    });


    static::deleted(function ($answer){
//       $answer->question->decrement('answers_count');

      //  kau best answer delete kore dile  onno arekta select korte parbo,atar jonna


        $question = $answer->question;
        $question->decrement('answers_count');
        if($question->best_answer_id === $answer->id){
            $question-> best_answer_id = NULL;
            $question->save();
        }


    });


  }




  //date Eloqurent

  public function getCreateDateAttribute($value)
  {
    return $this->created_at->diffForhumans() ;
  }




        //best answer select
      public function  getStatusAttribute(){

          return $this->id===$this->question->best_answer_id ? 'vote-accept' : '';

      }

      // best answer dekte parbo,jokn j question korce o best answer select korce
    public function getIsBestAttribute(){
        return $this->id === $this->question->best_answer_id ;
    }



    //Many To Many Polymorphic Relations, topic question and answer vote

    public function votes(){
        return $this->morphToMany(User::class,'votable')->withTimestamps();
    }



    public function  upVotes(){
        return $this->votes()->wherePivot('vote',1);
    }


    public function  downVotes(){
        return $this->votes()->wherePivot('vote',-1);
    }





//$appends ar kaj holo vue te jaigula undefined oigula pauano,jaigula elloqurent oigula pauano
    protected $appends=['create_date','body_html'];








}

app/Question.php
<?php

namespace App;
use App\User;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{


  // Mass Assignment
  protected $fillable= ['title','body'];


  // One to many(inverse)
  public  function user(){

    return $this->belongsTo('App\User');
  }

    // slug
  public function setTitleAttribute($value)
  {
    $this->attributes['title'] = $value;
    $this->attributes['slug'] = str_slug($value);
  }


    //Route Binding

  public function getUrlAttribute($value){
    return route('questions.show',$this->slug);
  }




  //date Eloqurent

  public function getCreateDateAttribute($value)
  {
    return $this->created_at->diffForhumans() ;
  }

   //unanswered,answered,answered-accepted

  public  function  getStatusAttribute(){

    if($this->answers_count > 0){

      if($this->best_answer_id){

        return 'answered-accepted';

      }
      return 'answered';


    }
    return 'unanswered' ;




  }



  // question body parse //purifier used clean( )
  public function getBodyHtmlAttribute(){

    return clean(\Parsedown::instance()->text($this->body));

  }






    // One To Many
  public function answers(){
    return $this->hasMany(Answer::class);
  }


   // best answer select

    public function bestAcceptAnswer(Answer $answer){
        $this->best_answer_id = $answer->id;
        $this->save();


    }




    //Many to many

    public function favorites(){
        return $this->belongsToMany('App\User','favorites')->withTimestamps();
    }






//         Eloquent accessor
//          method

    public function isFavorited(){
        return $this->favorites()->where('user_id',auth()->id())->count() > 0;
    }

    //method ta ke attribute a convert korbo

    public  function getIsFavoritedAttribute(){
        return $this->isFavorited();

    }

    // arekta attribute toiri korlam

    public  function getFavoritesCountAttribute(){

        return $this->favorites()->count();

    }


    //Many To Many Polymorphic Relations, topic question and answer vote

    public function votes(){
        return $this->morphToMany(User::class, 'votable')
            -> withTimestamps();
    }


    public function upVotes(){
        return $this->votes()->wherePivot('vote', 1);
    }
    public function downVotes(){
        return $this->votes()->wherePivot('vote', -1);
    }





//$appends ar kaj holo vue te jaigula undefined oigula pauano,jaigula elloqurent oigula pauano
    protected $appends=['create_date'];




}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;
use App\Http\Requests\QuestionRequest;
use App\User;
use Illuminate\Support\Facades\Auth;
use App\Http\Middleware\CheckRole;


class QuestionController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */




  /**
  1. php artisan make:middleware CheckRole

   2.CheckRole.php te
   use Illuminate\Support\Facades\Auth

   public function handle($request, Closure $next)
  {

  if (Auth::check() == false ){
  return redirect('/login');
  }

  return $next($request);
  }

  3. kernel.php te

  'CheckRole'=>\App\Http\Middleware\CheckRole::class

  */


  public function __construct(){
    return $this->middleware('CheckRole',['except'=>['index','show']]);
  }


//   public function __construct(){
//       return $this->middleware('auth',['except'=>['index','show']]);
//   }



  public function index()
  {
    $questions = Question::latest()->paginate(5);
    return view('questions.index',compact('questions'));

  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    $questions = new Question();
    $questions->user_id=Auth::id();
    return view('questions.create',compact('questions'));


  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(QuestionRequest $request)
  {


    $questions = new Question();
    $questions->user_id=Auth::id();
    $questions->title=$request['title'];
    $questions->body=$request['body'];
    $questions->save();

    return redirect()->route('questions.index')->
    with('success','Question submitted Successfully');




  }

  /**
  * Display the specified resource.
  *
  * @param  \App\Question  $question
  * @return \Illuminate\Http\Response
  */
  public function show(Question $question)
  {
    return view('questions.show',compact('question'));
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Question  $question
  * @return \Illuminate\Http\Response
  */

  public function edit(Question $question)
  {


//        if(\Gate::denies('update-question', $question)){
//            return abort(403, 'Access Denied');
//        }

    $this->authorize('update', $question);       //ata likbo,gate kete


    $question->user_id=Auth::id();
      return view('questions.edit',compact('question'));
  }


  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Question  $question
  * @return \Illuminate\Http\Response
  */

  public function update(QuestionRequest $request, Question $question)
  {

//        if(\Gate::denies('update-question', $question)){
//            return abort(403, 'Access Denied');
//        }


    $this->authorize('update', $question);       //ata likbo,gate kete


    $question->user_id=Auth::id();
    $question->title=$request['title'];
    $question->body=$request['body'];
    $question->save();

    return redirect()->route('questions.index')->
    with('success','Question Updated Successfully');

  }


  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Question  $question
  * @return \Illuminate\Http\Response
  */

  public function destroy(Question $question)
  {

//        if(\Gate::denies('delete-question', $question)){
//            return abort(403, 'Access Denied');
//        }

    $this->authorize('delete', $question);       //ata likbo,gate kete


    $question->user_id=Auth::id();
    $question->delete();
    return redirect()->route('questions.index')->
    with('success','Question Deleted Successfully');




  }


}

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <div class="float-left">
              <h3>Your Questions</h3>
            </div>


            <diV class="float-right mx-auto">

              <a href="{{route('questions.index')}}" class="btn btn-outline-success">Back to All Question</a>


            </diV>

          </div>

            <div class="card-body">
              <div class="media">
                <div class="media-body">



                  <form action="{{route('questions.store')}}"  method="POST" >
                    @csrf

                      @method("post")

                    <div class="form-group ">
                      <label for="title" >Question Title</label>

                        <input id="title" type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title') }}" required autofocus>

                        @if ($errors->has('title'))
                          <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('title') }}</strong>
                  </span>
                        @endif

                    </div>

                    <div class="form-group ">
                      <label for="body" >Question Body</label>

                      <textarea id="body"  type="text" rows="12" class="form-control{{ $errors->has('body') ? ' is-invalid' : '' }}" name="body" value="{{ old('body') }}" required></textarea>


                        @if ($errors->has('body'))
                          <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('body') }}</strong>
                  </span>
                        @endif


                    </div>

                        <button type="submit" class="btn btn-outline-success">Submit </button>

                  </form>






              </div>
              </div>
            </div>

        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <h3>Your Questions</h3>
                        </div>


                        <diV class="float-right mx-auto">

                            <a href="{{route('questions.index')}}" class="btn btn-outline-success">Back to All Question</a>


                        </diV>

                    </div>

                    <div class="card-body">
                        <div class="media">
                            <div class="media-body">



                                <form action="{{route('questions.update',$question->id)}}"  method="POST" >
                                    @csrf
                                    @method('put')



                                    <div class="form-group ">
                                        <label for="title" >Question Title</label>

                                        <input value="{{$question->title}}" id="title" type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title') }}" required autofocus>

                                        @if ($errors->has('title'))
                                            <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('title') }}</strong>
                  </span>
                                        @endif

                                    </div>

                                    <div class="form-group ">
                                        <label for="body" >Question Body</label>

                                        <textarea id="body"  type="text" rows="12" class="form-control{{ $errors->has('body') ? ' is-invalid' : '' }}" name="body" value="{{ old('body') }}" required>{{$question->body}}</textarea>


                                        @if ($errors->has('body'))
                                            <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('body') }}</strong>
                  </span>
                                        @endif


                                    </div>

                                    <button type="submit" class="btn btn-outline-success">Submit </button>

                                </form>






                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <div class="float-left">
              <h3>All Questions</h3>
            </div>


            <diV class="float-right mx-auto">

              <a href="{{route('questions.create')}}" class="btn btn-outline-success">Ask Question</a>


            </diV>

          </div>


          @include('layouts._message')


          @foreach($questions as $question)
            <div class="card-body">
              <div class="media">


                <div class="d-flex flex-column counters">

                 <div class="vote">
                   <strong>
                     {{$question->votes_count}}
                     {{ str_plural('vote') }}
                   </strong>
                 </div>

                  <div class="status {{$question->status}}">
                    <strong>
                      {{$question->answers_count}}
                      {{ str_plural('Answer') }}
                    </strong>
                  </div>

                  <div class="view">
                    <strong>
                      {{$question->views}}
                      {{ str_plural('view') }}
                    </strong>
                  </div>

                </div>




                <div class="media-body">
                  <h3 class="mt-0">
                    <a href="{{$question->url}}">
                      {{$question->title}}
                    </a>
                    <p class="lead">
                      Asked By <a href="{{$question->user->url}}">
                        {{$question->user->name}}
                      </a>
                      <small class="text-muted">
                        {{$question->create_date}}
                      </small>
                    </p>
                  </h3>
                  {{str_limit(strip_tags($question->body,350))}}
                </div>


                <div class="d-flex flex-column">


            {{--  @if(Auth::user()->can('update-question', $question))--}}

                  @can('update',$question)




                  <a href="{{route('questions.edit',$question->id)}}" class="btn btn-outline-success btn-sm mb-3">Edit</a>



                {{--     @endif--}}
                {{--    @if(Auth::user()->can('delete-question', $question))--}}

                  @endcan

                  @can('delete',$question)




                  <form class="form-delete d-inline" action="{{route('questions.destroy',$question->id)}}" method="post">
                    @method('DELETE')
                    @csrf
                    <button onclick="return confirm('Warning! Are You Sure want to delete? ')" class="btn btn-outline-danger btn-sm  " type="submit">Delete</button>
                  </form>
                {{-- @endif--}}

                  @endcan


                </div>





              </div>
            </div>
            <hr>
          @endforeach

        <!-- <div class="mx-auto">
{{--                {{$questions->links()}}--}}
          </div>-->
{{--                   {{$questions->links()}}--}}


          {{$questions->render()}}


        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
 <div class="row justify-content-center">
 <div class="col-md-12">
  <div class="card">
  <div class="card-body">

   <div class="card-title">
   <div class="d-flex align-items-center">
    <h3>{{$question->title}}</h3>
    <h3 class="ml-auto">
    <a class="btn btn-outline-secondary" href="{{route('questions.index')}}">Back To All Question</a>

    </h3>
   </div>
   </div>
   <hr>
   <div class="media">

   {{-- question  votes-part  --}}

    <div class="d-flex flex-column votes-control">
        <a class="vote-up
    {{Auth::guest() ? 'off' : ''}}" onclick="event.preventDefault(); document.getElementById('questions-vote-up{{$question->id}}').submit()">
            <i  class=" fa fa-caret-up fa-3x"></i>
        </a>
        <span class="votes-count">
                                    {{$question->votes_count}}
                                </span>

        <form action="/questions/{{$question->id}}/vote " id="questions-vote-up{{$question->id}}" style="display: none" method="post">
            @csrf
            <input type="hidden" name="vote" value="1">



        </form>

{{--        <span class="votes-count">1205</span>--}}

        <a class="vote-down
                        {{Auth::guest() ? 'off' : ''}}" onclick="event.preventDefault(); document.getElementById('questions-vote-down{{$question->id}}').submit()">

            <i class=" fa fa-caret-down fa-3x"></i>
        </a>

        <form action="/questions/{{$question->id}}/vote " id="questions-vote-down{{$question->id}}" style="display: none" method="post">
            @csrf
            <input type="hidden" name="vote" value="-1">



        </form>

        <a  onclick="event.preventDefault(); document.getElementById('questions-favorites-{{$question->id}}').submit()"
            class="favourite mt-3
        {{Auth::guest() ? 'off' :($question->is_favorited) ? 'fabs': '' }}  ">
            <i class=" fas fa-star fa-2x"></i>

            <span class="faboritted">
                                    {{$question->favorites_count}}

                                </span>

        </a>

        <form action="/questions/{{$question->id}}/favorites " id="questions-favorites-{{$question->id}}" style="display: none" method="post">
            @csrf

            @if($question->is_favorited)

                @method('DELETE')
            @endif

        </form>


    </div>

    {{-- question  votes-part end --}}


    <div class="media-body">

    {!! $question->body_html !!}
    <div class="float-right">

        {{--   vue  --}}

        <user-info label="Asked" :model="{{$question}}" ></user-info>

        {{--   vue  end--}}


    </div>
   </div>
   </div>
  </div>
  </div>
 </div>
 </div>






 {{--------------------------- <answer part> ---------------------}}


 <div class="row mt-5" v-cloak>

 <div class="col-md-12">
  <div class="card">
  <div class="card-body">
   <div class="card-title">
       <h3>

    <h2>Your Answer</h2>
    @include('layouts._message')

    <form action="{{route('questions.answers.store',$question->id)}}" method="post">
     @csrf
     <div class="form-group">
      <textarea rows="7" class="form-control {{ $errors->has('body') ? ' is-invalid' : '' }}" name="body"></textarea>


      @if ($errors->has('body'))
       <span class="invalid-feedback" role="alert">
     <strong>{{ $errors->first('body') }}</strong>
       </span>
      @endif

     </div>
     <div class="form-group">
      <button class="btn btn-outline-success  " type="submit">SUBMIT</button>
     </div>

    </form>

    {{$question->answers_count}} {{ str_plural('Answer') }}
       </h3>

   <hr>
   @foreach($question->answers as $answer)
    <div class="media">


     {{-- answers  votes-part  --}}

     <div  class="d-flex flex-column votes-control">
         <a class="vote-up
                               {{Auth::guest() ? 'off' : ''}}"

            onclick="event.preventDefault(); document.getElementById('answers-vote-up{{$answer->id}}').submit()">
             <i class="fas fa-caret-up fa-3x"></i>
         </a>
         <span class="votes-count">
                                {{$answer->votes_count}}
                            </span>
         <form action="/answers/{{$answer->id}}/vote" id="answers-vote-up{{$answer->id}}"
               style="display: none" method="post">
             @csrf
             <input type="hidden" name="vote" value="1">
         </form>

{{--         <span class="votes-count">1205</span>--}}

         <a class="vote-down
                               {{Auth::guest() ? 'off' : '' }}"
            onclick="event.preventDefault(); document.getElementById('answers-vote-down{{$answer->id}}').submit()">
             <i class="fas fa-caret-down fa-3x"></i>
         </a>
         <form action="/answers/{{$answer->id}}/vote" id="answers-vote-down{{$answer->id}}"
               style="display: none" method="post">
             @csrf
             <input type="hidden" name="vote" value="-1">
         </form>

         {{-- best answer select --}}

         @can('accept',$answer)

      <a class="favourite mt-3  {{$answer->status}}"

         onclick="event.preventDefault(); document.getElementById('accept-answer-{{$answer->id}}').submit()">
       <i class=" fas fa-check fa-2x"></i>

       {{-- <span class="faboritted">1234</span>--}}

      </a>
          <form action="{{route('accept.answers',$answer->id)}}" id="accept-answer-{{$answer->id}}" style="display: none" method="post">
              @csrf

          </form>

         @else
             @if($answer->is_best)

                 <a class="favourite mt-3 {{$answer->status}}">

                 <i class=" fas fa-check fa-2x"></i>
                 </a>

             @endif


             @endcan

     </div>

     {{-- answers  votes-part end  --}}

        {{-- .............................................................. --}}

        <answer :answer="{{$answer}}" inline-template>

       <div class="media-body">

                {{--    {!! $answer->body_html !!}  --}}    {{--  parse korci--}}



           <form v-if="editing" @submit.prevent="update">

       <div class="form-group">

        <textarea required v-model="body" rows="10" class="form-control" ></textarea>       {{-- $answer->answer->body--}}

       </div>

       <button :disabled="isInvalid"  class="btn btn-outline-success" >update</button>
       <button  class="btn btn-outline-secondary" @click="cancel" >Cancel</button>

           </form>


     <div v-else>

         <div v-html="bodyHtml"></div>


     <div class="row">



      <div class="col-md-4">

       <div class="ml-auto">       {{-- d-flex flex-column float-left--}}
         @can('update',$answer)

               <a @click.prevent="edit" class="btn btn-outline-success btn-sm mb-3 d-inline">Edit</a>

               {{--href="{{route('questions.answers.edit',[$question->id,$answer->id])}}"--}}


           @endcan
         @can('delete',$answer)

{{--         <form class="form-delete d-inline" action="{{route('questions.answers.destroy',[$question->id,$answer->id])}}"  method="post">--}}
{{--          @method('delete')--}}
{{--          @csrf--}}
{{--          <button onclick="return confirm('Warning! Are You Sure want to delete? ')" class="btn btn-outline-danger btn-sm  " type="submit">Delete</button>--}}
{{--         </form>--}}

             <button @click="destroy" class="btn btn-sm btn-outline-danger">Delete</button>


         @endcan

       </div>



      </div>


       <div class="col-md-4">

       {{--   empty  --}}

      </div>


          {{--  Answer ->user name,answered date &avatar--}}

      <div class="col-md-4">
       <div class="float-right">

           {{--   vue  --}}
           <user-inf label="" :model="{{$answer}}" ></user-inf>

           {{--   vue  end--}}

       </div>
      </div>
       {{--  Answer ->user name,answered date &avatar End--}}


     </div>

     </div>

    </div>

        </answer>

{{--   .............................................................. --}}


    </div>
    <hr>

   @endforeach
   </div>

  </div>
  </div>

 </div>
 </div>

</div>


@endsection